baseURL = 'https://haiyinglan.github.io/hugonews/'
languageCode = 'en-us'
title = '我的网站'
theme = 'ananke'
publishDir = "docs"

[markup]
  defaultMarkdownHandler = "goldmark"

[markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true